server:
  port: 8888
spring:
  application:
    name: application
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./config
  profiles:
    active: native
